server:
  port: 8084
spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
        - id: car
          uri: lb://CAR
          predicates:
            - Path=/api/v1/cars/**
        - id: storage
          uri: lb://STORAGE
          predicates:
            - Path=/api/v1/storage/**

service:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true